######
FROM quay.io/centos/centos:stream8 as centos8-builder

RUN yum install -y \
     gcc pcre-devel zlib-devel make openssl-devel

COPY configure /tmp
COPY config /tmp
COPY Makefile /tmp
COPY src/* /tmp/src/
ARG NGINX_VERSION
ENV NGINX_VERSION=$NGINX_VERSION
ADD nginx-$NGINX_VERSION.tar.gz /tmp/

WORKDIR /tmp
RUN ./configure && make

######
FROM alpine

ARG NGINX_VERSION
ENV NGINX_VERSION=$NGINX_VERSION
COPY --from=centos8-builder /tmp/nginx-$NGINX_VERSION/objs/ngx_curity_http_oauth_proxy_module.so /build/centos.8.ngx_curity_http_oauth_proxy_module_$NGINX_VERSION.so

ENTRYPOINT ["sleep"]
CMD ["300"]
