##############################################################################
# Deploy a Docker containers and run it via valgrind, to test for memory leaks
##############################################################################

version: '3.8'
services:

  custom_nginx:
    image: nginx_${DISTRO}:${NGINX_VERSION}
    ports:
    - 8081:8081
    volumes:
    - ./nginx.conf:${CONF_PATH}
    - ../../build/${MODULE_FILE}:${MODULE_FOLDER}/ngx_curity_http_oauth_proxy_module.so
    command: >
      sh -c "/usr/bin/valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=/valgrind-results.txt ${NGINX_PATH}"
